### ISSUE TITLE
How can I get the outputs of the chalice construct?

### ISSUE THREAD

**Issue by royby-cyberark** [alexpulver/cdk-chalice#12]
Hi, 
I am trying to get the API Gateway ID that chalice creates and which it add to the cloudFormation template in the "Outputs" section.
I tried many things, but nothing worked. 
Here are some of the things I tried:
1. inspecting the chalice construct,: node, children, etc, but nothing seem to contain this.
2. using the core.Fn functions to get some info from the CF:  
core.Fn.get_att('RestAPI', 'RestAPIId')
core.Fn.ref('AWS::ApiGateway::RestApi')
core.Fn.ref('AWS::ApiGateway::RestApi::Id')
core.Fn.get_att('Outputs.RestAPIId', 'RestAPI')
core.Fn.ref('ApiGatewayRestApi')

but everything ends with an error ' Template format error: Unresolved resource dependencies'

3. I also tried looking for the outputs in the stack, Stack.of(self).node

I would like to understand how to get the rest api id of the chalice object (that is written to the Outputs section of the CF).

Thanks!

**Comment by royby-cyberark** [comment]
As I work around it possible to deploy these changes in another stack, reading the output of the stack using boto3.cloudformation.describe_stacks and using that.
if possible, I would love to do it in the original stack, without resorting to run another stack just for that.

**Comment by royby-cyberark** [comment]
I was able to get this to work. 
I looked at deployed stack CF template, and saw this:

```
APIHandlerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: APIHandler
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub:
          - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPIId}/*
          - RestAPIId:
              Ref: RestAPI
```

I then changed my code to reference the RestAPIId like so:

`rest_api_id = core.Fn.ref("RestAPI")`

This did the trick.
